name: flutterapparbol
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Icono para IOS
  cupertino_icons: ^0.1.3
  # Service dependency injection
  get_it: ^5.0.1
  injectable: ^1.0.5
  # Bloc for state management
  #flutter_bloc: ^0.21.0
  flutter_bloc: ^3.2.0
  #bloc: ^6.1.0
  #flutter_bloc: ^6.1.1
  # Value equality NO CAMBIAR A VERSION NUEVA PORQUE DESTRUYE GEOLOCATOR
  equatable: ^0.4.0
#  equatable: ^1.2.3
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4
  # Google Maps
  google_maps_flutter: ^0.5.28+1
  # NFC funcionalidades
  flutter_nfc_reader: ^0.1.0
  # NFC funcionalidades otro paquete
  nfc_in_flutter: ^2.0.5
  # Geolocator funcionalidades
  geolocator: ^6.0.0+4
  # Base de datos dispositivo
  sqflite: ^1.3.1+1
  # Encuentra rutas donde se guarda
  path: ^1.7.0
  # Dependencias curso https://www.youtube.com/watch?v=t39VV2XyqR0
  path_provider: ^1.6.14
  intl: ^0.16.1
  # identificadores unicos
  uuid: ^2.2.2
  # para sacar fotos
  image_picker: ^0.6.7+11
  # Para formato letras
  google_fonts: ^1.1.1
  # Para uniones
  freezed_annotation: ^0.12.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  #Para reemplazo de los snack bar
  flushbar: ^1.10.4
  #Para hacer rutas de navegacion
  auto_route: ^0.6.9


dev_dependencies:
  build_runner: ^1.10.4
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  # Para uniones
  freezed: ^0.12.2
  lint: ^1.1.1
  injectable_generator: ^1.0.6
  auto_route_generator: ^0.6.10

flutter:

  uses-material-design: true


