import 'package:flutterapparbol/features/arbol/domain/entities/arboles_entity.dart';

final ArbolEntity arbolVacio = ArbolEntity(
  guiArbol: "No asignado",
  idArbol: 0,
  idNfcHistoria: [],
  clienteArbol: "No asignado",
  zonaArbol: "No Asignada",
  calleArbol: "No Asignada",
  nCalleArbol: null,
  esquinaCalleArbol: "No Asignada",
  especieArbol: "No Asignada",
  diametroTroncoArbolCm: null,
  diametroCopaNsArbolMt: null,
  diametroCopaEoArbolMt: null,
  alturaArbolArbolMt: null,
  alturaCopaArbolMt: null,
  estadoGeneralArbol: "No determinado",
  estadoSanitarioArbol: "No determinado",
  enfermedad: Enfermedad(),
  inclinacionTroncoArbol: "No determinado",
  orientacionInclinacionArbol: "No determinado",
  obsArbolHistoria: [],
  accionObsArbol: "No Asignada",
  segundaAccionObsArbol: "No Asignada",
  terceraAccionObsArbol: "No Asignada",
  geoReferenciaCapturaArbol: null,
  nombreUsuarioCreacionArbol: "No Asignada",
  usuarioModificaArbol: "No Asignada",
  fechaCreacionArbol: null,
  fechaUltimaModArbol: null,
  alertaArbol: "No Asignada",
  revisionArbol: "No Asignada",
  fotosArbol: [],
  fotosEnfermedad: [],
);
